# Generated by Django 4.1.7 on 2023-04-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_author_product_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="address",
            field=models.CharField(
                blank=True, default="Baku", max_length=50, null=True
            ),
        ),
    ]
