# Generated by Django 4.1.7 on 2023-04-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_author_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="surname",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
